import { Link } from "react-router-dom";
import Reveal from "../components/Reveal";
import { site } from "../data/site";

export default function About() {
  return <>
    <section className="section shell page-head"><div className="section-kicker">ABOUT / BYTES</div><div className="intro-grid"><Reveal><h1 className="display">A software engineering agency for useful, serious products.</h1></Reveal><div><Reveal><p className="body-xl">{site.description}</p></Reveal><Reveal><p className="body-copy">We work across product design, frontend systems, backend architecture, data, integrations and applied AI. The goal is simple: build software that solves a real problem and remains understandable after launch.</p></Reveal><div className="capability-row">{site.capabilities.map(c=><span key={c}>{c}</span>)}</div><div className="manifest"><div className="manifest-row"><small>GITHUB</small><strong><a href="https://github.com/xolo177013" target="_blank" rel="noopener noreferrer">github.com/xolo177013 ↗</a></strong></div><div className="manifest-row"><small>BASE</small><strong>{site.location}</strong></div><div className="manifest-row"><small>MODEL</small><strong>Agency · direct collaboration</strong></div><div className="manifest-row"><small>WORK</small><strong>Full-stack products · SaaS · AI · automation · internal tools</strong></div><div className="manifest-row"><small>CONTACT</small><strong><a href={`mailto:${site.email}`}>{site.email}</a></strong></div></div></div></div></section>
    <section className="section architecture"><div className="shell"><div className="section-kicker">01 / PRINCIPLES</div><div className="arch-grid"><Reveal><h2 className="display">Use complexity where it creates leverage.</h2></Reveal><div className="system">{["Start with the constraint","Design the system and interface together","Prefer boring infrastructure where it wins","Leave the product easier to change"].map((x,i)=><div className="sys-row" key={x}><span className="num">0{i+1}</span><div><h4>{x}</h4><p>{["Users, business rules, latency, budget and team capability shape the solution.","A loading state, API boundary or database decision can change the user journey.","Use complexity when it creates real leverage, not because the stack looks impressive.","Readable code, explicit boundaries, documented decisions and repeatable delivery matter after launch."][i]}</p></div></div>)}</div></div></div></section>
    <section className="section shell"><div className="section-kicker">02 / TOOLBOX</div><div className="intro-grid"><Reveal><h2 className="display">A practical stack, chosen per problem.</h2></Reveal><div className="manifest"><div className="manifest-row"><small>FRONTEND</small><strong>React · Next.js · TypeScript</strong></div><div className="manifest-row"><small>BACKEND</small><strong>Python · Django · Django REST Framework · Node.js</strong></div><div className="manifest-row"><small>DATA</small><strong>PostgreSQL · MongoDB · Redis · REST APIs</strong></div><div className="manifest-row"><small>AI</small><strong>LLM APIs · RAG · Vector search · document workflows</strong></div><div className="manifest-row"><small>SHIP</small><strong>Git · GitHub · Docker · Linux · CI/CD</strong></div></div></div></section>
    <section className="contact-section"><div className="shell contact-grid"><h2 className="display">Have a useful problem?</h2><Link className="button" to="/contact">Talk to Bytes ↗</Link></div></section>
  </>;
}